multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./stocks.py", line 39, in get_stock_info
    name = soup.title.text.split('|')[0]
AttributeError: 'NoneType' object has no attribute 'text'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./stocks.py", line 167, in <module>
    stocks = pool.map(get_stock_info, stock_urls)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'text'
2926.97user 58.61system 50:18.37elapsed 98%CPU (0avgtext+0avgdata 56644maxresident)k
22496inputs+1776outputs (68major+1405373minor)pagefaults 0swaps
